### ISSUE TITLE
SERIAL is unknown

### ISSUE THREAD

**Issue by debonil** [apache/cordova-plugin-device#116] opened 2020-01-17 08:28 UTC
Hello

I am using this plugin in Ionic 3 Project for Android Platform. Reading device IMEI and hardware serial number is our requirement.  But not able to read hardware serial number with this plugin. Getting the value 'unknown'. Please help.

**Comment by timbru31** [comment] 2020-01-17 10:59
This is a duplicate of #111

**Closed by timbru31** 2020-01-17 10:59 UTC
