### ISSUE TITLE
IOS: Device UUID change each time  delete App and reinstall

### ISSUE THREAD

**Issue by digital-tcbs** [apache/cordova-plugin-device#117] opened 2020-02-26 05:25 UTC
# Bug Report
IOS: Device UUID change each time  delete App and reinstall.
## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by rr-philips** [comment] 2020-09-30 12:58
I'm pretty sure that this is standard behavior for ios apps, not just this plugin?

**Comment by faugusztin** [comment] 2020-09-30 13:50
The reason is described in the documentation under [iOS quirk](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-device/index.html#ios-quirk):

> The uuid on iOS uses the identifierForVendor property. It is unique to the device across the same vendor, but will be different for different vendors and will change if all apps from the vendor are deleted and then reinstalled. Refer here for details. The UUID will be the same if app is restored from a backup or iCloud as it is saved in preferences. Users using older versions of this plugin will still receive the same previous UUID generated by another means as it will be retrieved from preferences.

**Comment by breautek** [comment] 2020-09-30 13:56
Thank you for the responses and providing the link that explains the reason for the behavior.

I'm closing this issue as not a bug/wont fix.

**Closed by breautek** 2020-09-30 13:56 UTC
