### ISSUE TITLE
UUID in debug and release mode is different

### ISSUE THREAD

**Issue by kyoz** [apache/cordova-plugin-device#112] opened 2019-12-06 10:10 UTC
# Bug Report

### What is expected to happen?

UUID is the same when debug and release cause that's uuid of device, doesn't have any thing relative to the app

### What does actually happen?

In development, build debug, release, they have different UUID, is this valid ?

### Environment, Platform, Device
Environment: Linux
Platform: Android
Device: Xiaomi Mi 8 Lite

### Version information
Everything is latest
SDK 26 (OREO)

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by ericgopak** [comment] 2020-10-28 12:00
This doesn't seem to be a bug, but rather an expected behavior: unfortunately UUIDs may change between app installs (which you perform when you switch between debug and release).

References for iOS: [StackOverflow](https://stackoverflow.com/questions/40753246/ios-uuid-different-for-same-app-depending-if-installed-through-xcode-or-testflig/40753810#40753810), [Apple docs](https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor)

References for Android: [StackOverflow](https://stackoverflow.com/a/2785493), [Android docs](https://developer.android.com/training/articles/user-data-ids)

**Comment by breautek** [comment] 2020-10-28 12:36
Thank you @ericgopak for investigating and providing links to relevant documentations. It does appear that this is the expected behaviour.

I think the Cordova documentation is out-dated:

> The details of how a UUID is generated are determined by the device manufacturer and are specific to the device's platform or model.

I believe this may be remnants of how UUIDs worked on Android Pre API 26, where the UUIDs were essentially completely based on signing key so as long as the same signing key, you had the same UUID. Since Google Play requires API >= 29 (Effective November), I think we can update our documentation. PRs are welcome for anybody willing to make this change.

**Comment by jcesarmobile** [comment] 2022-09-06 19:05
This has been documented, so closing
https://github.com/apache/cordova-plugin-device#android-quirk

**Closed by jcesarmobile** 2022-09-06 19:05 UTC
